spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.19.26.22:3306/sbc-bff?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: Wmi@2023
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      max-lifetime: 30000
      idle-timeout: 30000
      connection-timeout: 30000
      validation-timeout: 15000
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: true
  sql:
    init:
      continue-on-error: false

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: >
    com.liguang.mytest.entry

server:
  port: 8080
  # 设置http 请求编码为utf-8
#  tomcat:
#    uri-encoding: UTF-8
#  servlet:
#    encoding:
#      force-request: true
#      charset: UTF-8
#      enabled: true
#      force-response: true

management:
  server:
    port: 6000
  health:
    mail:
      enabled: false

jasypt:
  encryptor:
    password: helloworld

#nacos:
#  config:
#    server-addr: 172.19.26.22:8848
#    data-id: test
#    bootstrap:
#      enable: false
#    ext-config:
#      - data-id: ext-test
#        type: properties
#        autoRefresh: true
#    auto-refresh: true

gts:
  page-size: 20
  cookie: _samesite_flag_=true; cookie2=15efca9d97b2e97854b2eef7c473caab; t=d6e80b17214acf646c7ffbe8c9b234ba; _tb_token_=584e349bbed31; aliyun_lang=zh; aliyun_site=CN; currentRegionId=cn-beijing; _uab_collina=167687905115275991865551; _umdata=G652E46864EC74FC94CF76F7E71694C72F7CABD; activeRegionId=cn-beijing; help_csrf=fT8QmBcrXiue2ZdFKGRyPlqoizOwAmkqT8cu1rMtJ37NLevKBndDe2bfVwUxsyCqJuLLiGAPvN5wV96U5eKv4s6SP%2FW%2B1q6CsPNbENZW%2BKmHfQS7jIqws%2B8zyDUEelPpK%2FfRmF0BlBYYX%2Bzl6Oa5jA%3D%3D; cr_token=ecbc3dd7-6ec0-447b-ad1f-1c280d50db40; aliyun_choice=CN; console_base_resource_group_id=rg-aek26hjbmheacuy; login_aliyunid_csrf=_csrf_tk_1615776876248043; login_aliyunid="liguang @ 1148061705306549"; login_aliyunid_ticket=jtFCGjZQKNuN1Q3Z5X4DmWIIQKxAD4jJyAD0FKUwIkkfq1S1E2ml6JYlY4q9CyLstMknfiSc2GhOwNcWzj5bYLpKzKZ49O80KpzxYXWJ0WPzFXDzr7rhZ_Dua5Qyv2KMv85szYAdhP4$; login_aliyunid_sc=74u48x24xL7xCj1SQ9*cYL0T_GM6j7559x2VmxUCiFGw3VB*HCWIQqccRv4BWNrY56CirX_*9VBpfkTFdJTd5x4Am*onCKGpjzWdKRzKjHfrmJK*H1vT5ERPp2356A*R; COS_JSESSIONID=X6866Q91-Y7371UD7EYSKBCY45T723-5AFJCEEL-7337; _cos_session0=B00PXHVwLxUgEy%2FifoWEBffiPSiIXBCmcPAxu9X22zsgWfhc5f0PTtcbcMXs1HaD4cubeNGU5cG%2BCEmBGzOpySX2L5deMdNbS4UHi1WpRMeuSM5dMMOXjt%2BnFpCqEoNLpcgYsoKY2tc2MeeQCJT8u85YkpI9%2BBr7IJ6mFayHyLIZSe%2B2i3fVTG9eWixgXvyZffo43IhoX%2Bc3Vp9P7WTXXNjr1yeHiL3nBN5oCHz0ZejRmBsk7YmkLfkYh4fcmOqnGeS03Lzmx0YUKoEHqL1bA5VCruTGU%2FkeYHHJYaHwnG0zTlimel9PoVUpqZKpgIn5; l=fBTjswvmT60C9u5MmO5Ilurza77TzBOXckPzaNbMiIEGa66D9_uWyNCeyvrNWdtfgTfYDetyPFnHmdUJrqaLSx98S8d60X6oT6J6-bpU-L5..; tfstk=c90OBNbAwBCtnSv08PKh0SOcdF0VaPT4dOwfk4P95_nF-1Qh8sDor4dkxFN0URdd.; isg=BDIyLdyGhbly0LnW_u2PS33Lg34UwzZd4MomUfwMAuWJj8KJ5FaNbe-pf6sz5K71
  sec-token: bWlbwVITkxBU8OuXzWB2J
  collina: collina
  um-id: Y984dd8b8aebc4f0bf820f975e8eb8725
  # kafka_topics
  kafka-topics: sbc-customer.company_info,sbc-goods.goods,sbc-goods.goods_info,sbc-goods.goods_cate,sbc-goods.goods_brand,sbc-goods.store_cate,sbc-goods.store_cate_goods_rela,sbc-goods.goods_info_spec_detail_rel,sbc-customer.customer,sbc-customer.customer_detail,sbc-customer.customer_level,sbc-customer.employee,sbc-customer.store,sbc-customer.store_customer_rela,sbc-customer.store_level,sbc-account.customer_funds,sbc-order.goods_customer_follow_action,sbc-order.purchase_action,sbc-marketing.coupon_activity,sbc-marketing.coupon_activity_config,sbc-marketing.coupon_code_0,sbc-marketing.coupon_code_1,sbc-marketing.coupon_code_2,sbc-marketing.coupon_code_3,sbc-marketing.coupon_code_4,sbc-marketing.coupon_info,sbc-marketing.booking_sale,sbc-marketing.booking_sale_goods,sbc-goods.flash_sale_goods,sbc-marketing.appointment_sale,sbc-marketing.appointment_sale_goods,sbc-goods.groupon_goods_info,sbc-goods.groupon_share_record,sbc-marketing.marketing,sbc-marketing.marketing_scope,sbc-marketing.groupon_activity,sbc-customer.customer_delivery_address,sbc-customer.customer_points_detail,sbc-customer.third_login_relation,sbc-setting.system_config,sbc-setting.platform_address,sbc-account.customer_funds,sbc-account.customer_funds_detail,sbc-marketing.coupon_marketing_scope,sbc-marketing.groupon_activity,sbc-marketing.coupon_marketing_customer_scope,sbc-goods.goods_spec,sbc-order.refund_order,sbc-customer.wechat_video_user,sbc-customer.paying_member_customer_rel,sbc-order.paying_member_record,sbc-marketing.bargain_goods,sbc-marketing.marketing_buyout_price_level,sbc-marketing.marketing_half_price_second_piece,sbc-marketing.marketing_suits,sbc-marketing.marketing_suits_sku,sbc-goods.live_streaming_goods,sbc-goods.live_streaming_goods_detail,sbc-goods.live_session_check,sbc-customer.store_creator_rel

# mybatis-plus 配置

